Update classroom.yaml

diff --git a/.github/workflows/classroom.yaml b/.github/workflows/classroom.yaml
--- a/.github/workflows/classroom.yaml
+++ b/.github/workflows/classroom.yaml
@@ -25,10 +25,17 @@ jobs:
     
       - name: Install requirements
         run: pip install -r requirements.txt
+
+      - name: Debug - run pytest verbosely
+        run: |
+          pytest -vv || true      # don't fail job, just print traceback
     
       - name: Run unit tests
         id: tests
         uses: classroom-resources/autograding-python-grader@v1
         with:
+          entryPoint: pytest
+          args: "-q"
           timeout: 10
           pytest-options: "-p no:runner.orderplugin"
+          setup-command: "pip install -r requirements.txt"
